name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username ${{ secrets.AWS_ECR_DOCKER_USERNAME }} --password-stdin ${{ secrets.AWS_ECR_DOCKER_PASSWORD_STDIN }}
          rev=$(git rev-parse --short HEAD)
          docker build . -t hello
          docker tag hello ${{ secrets.AWS_ECR_DOCKER_PASSWORD_STDIN }}/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:$rev
          docker push ${{ secrets.AWS_ECR_DOCKER_PASSWORD_STDIN }}/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:$rev
